@Policlinic.Server_HostAddress = http://localhost:5204

GET {{Policlinic.Server_HostAddress}}/todos/
Accept: application/json

###

GET {{Policlinic.Server_HostAddress}}/todos/1
Accept: application/json

###
